# Generated by Django 4.2.3 on 2023-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
                ('dpi', models.CharField(max_length=13)),
            ],
        ),
    ]
